### ISSUE TITLE
BrokenResourceError

### ISSUE THREAD

**Issue by SarloAkrobata** [tiangolo/fastapi#4041]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the FastAPI documentation, with the integrated search.
- [X] I already searched in Google "How to X in FastAPI" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to FastAPI but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to FastAPI but to [Swagger UI](https://github.com/swagger-api/swagger-ui).
- [X] I already checked if it is not related to FastAPI but to [ReDoc](https://github.com/Redocly/redoc).

### Commit to Help

- [x] I commit to help with one of those options 👆

### Example Code
app.py
```python
import time
import uvicorn
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware


app = FastAPI()


@app.middleware("http")
async def middleware(request: Request, call_next):
    return await call_next(request)


@app.get("/")
def read_root():
    time.sleep(4)
    return {"Hello": "World"}


if __name__ == "__main__":
    uvicorn.run(app="app:app", port=8000)
```
script.py
```python
import requests as requests

r = requests.get(f"http://127.0.0.1:8000", timeout=2)
```

### Description
If you trigger script.py, error will appear.
After upgrade fastapi to 0.70.0 In some requests in our application its apearing this error.  So what we can do? What is problem?
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "venv/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "venv/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "venv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "venv/lib/python3.8/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "venv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "venv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "venv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "venv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "venv/lib/python3.8/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "venv/lib/python3.8/site-packages/starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "venv/lib/python3.8/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "venv/lib/python3.8/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
anyio.BrokenResourceError
```

### Operating System

Linux

### FastAPI Version

0.70.0

### Python Version

3.8

**Comment by WouldYouKindly** [comment]
This looks like a starlette issue: https://github.com/encode/starlette/issues/1284

**Comment by tonal** [comment]
```
Exception in ASGI application
BrokenResourceError: null
  File "uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "starlette/exceptions.py", line 82, in __call__
    raise exc
  File "starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "starlette/exceptions.py", line 68, in sender
    await send(message)
  File "anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
```
### Operating System
Linux
### FastAPI Version
0.70.0

### Python Version
3.9.7

**Comment by alejosv** [comment]
I have the same problem, this is my code:

**main.py**
```
# -*- coding: utf-8 -*-


from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse
from fastapi.encoders import jsonable_encoder
from pony.orm import *

from models_pony.name_basics import NameBasics as pn_name_basics

api = FastAPI() 


@api.middleware('http')
async def process_request(request: Request, call_next):
    return await call_next(request)


@api.get('/namebasics/id/{id}')
async def get_namebasic_by_id(id:int):
    with db_session:
         result = (pn_name_basics[id]).to_dict()
    return JSONResponse(result)



@api.get('/namebasics/ncost/{ncost}')
async def get_namebasic_by_ncost(ncost:str):
    with db_session:
        result = (pn_name_basics.get(ncost=ncost)).to_dict()
    return JSONResponse(result)



@api.get('/namebasics/year/{year}')
async def get_namebasic_by_year(year:str):
    with db_session:
        results = select(p for p in pn_name_basics if p.birth_year == year)[:]
        _results = [i.to_dict() for i in results]
        _results = jsonable_encoder(_results)
    return JSONResponse(_results)



@api.get('/namebasics/yearalive/{yearalive}')
async def get_namebasic_by_yearalive(yearalive:str):
    with db_session:
        results = select(p for p in pn_name_basics if p.birth_year == yearalive and p.death_year is None)[:]
        _results = [i.to_dict() for i in results]
        _results = jsonable_encoder(_results)
    return JSONResponse(_results)
```

**Command terminal test**
```
wrk --duration 20s --threads 2 --connections 5 http://0.0.0.0:8000/namebasics/id/1024
Running 20s test @ http://0.0.0.0:8000/namebasics/id/1024
  2 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     8.54ms    9.84ms 112.06ms   91.46%
    Req/Sec   289.56    154.88   565.00     59.00%
  11538 requests in 20.05s, 3.66MB read
Requests/sec:    575.56
Transfer/sec:    187.17KB
```

**Error**
```
[2021-10-20 01:50:45 +0000] [5117] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 604, in _run_wrapped_task
    await coro
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
anyio.BrokenResourceError
[2021-10-20 01:50:45 +0000] [5117] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 604, in _run_wrapped_task
    await coro
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
anyio.BrokenResourceError
[2021-10-20 01:50:45 +0000] [5116] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 604, in _run_wrapped_task
    await coro
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
anyio.BrokenResourceError
[2021-10-20 01:50:45 +0000] [5116] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/_backends/_asyncio.py", line 604, in _run_wrapped_task
    await coro
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/lxcshared/benchmark.git/Python/src/.venv/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
anyio.BrokenResourceError
```

Something that strikes me is that the application does not crash. The error is not displayed if I **remove the middleware** and the performance of the requests is better.

**Test 1**
```
wrk --duration 20s --threads 2 --connections 5 http://0.0.0.0:8000/namebasics/id/1024
Running 20s test @ http://0.0.0.0:8000/namebasics/id/1024
  2 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.42ms    5.01ms  90.24ms   92.50%
    Req/Sec   807.40    461.95     1.66k    54.25%
  32149 requests in 20.02s, 10.21MB read
Requests/sec:   1606.09
Transfer/sec:    522.29KB
```

**Test 2**
```
wrk --duration 20s --threads 2 --connections 5 http://0.0.0.0:8000/namebasics/id/1024
Running 20s test @ http://0.0.0.0:8000/namebasics/id/1024
  2 threads and 5 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.33ms    4.77ms  60.69ms   95.11%
    Req/Sec     1.34k   326.30     1.85k    87.75%
  53350 requests in 20.00s, 16.94MB read
Requests/sec:   2666.88
Transfer/sec:    867.27KB
```

**Comment by havardthom** [comment]
This is fixed in Starlette v0.17.0, hopefully FastAPI bumps starlette again on next release

**Comment by iamnotagentleman** [comment]
any progress? i have same problem too

**Comment by ixuuux** [comment]
I hide the error message like this:
```python
async def _hide_anyio_BrokenResourceError(*args, **kwargs):
    # hide `anyio.BrokenResourceError`
    pass

@app.middleware('http')
async def before_each_endpoint(request: Request, call_next: RequestResponseEndpoint):
    response = await call_next(request)
    if await request.is_disconnected():
        # hide `anyio.BrokenResourceError`
        return _hide_anyio_BrokenResourceError
    return response
```

But I don’t know the hidden dangers of doing this

**Comment by alejosv** [comment]
@ixuuux I think hide the error message it isn't recommended, definitely something wrong happening and this could produce unexpected behaviors, so I do think it's dangerous IMHO.

**Comment by ixuuux** [comment]
@alejosv Thank you, I am also worried about hiding error messages, so I don’t plan to do this.

**Comment by Actticus** [comment]
i catch same error with fastapi==0.70. is there any progress?

**Comment by Kvasela** [comment]
I've catched the same error with fastapi==0.70
When fastapi configured through gunicorn with uvicorn worker and behind **nginx** with **proxy_pass upstream** over **unix socket**.
In such configuration when **xhr request** becomes canceled (in browser) throws BrokenResourceError
![Canceled requests](https://user-images.githubusercontent.com/3797413/146207958-733bb3e3-fd13-4627-b623-36407a34d9ca.png)

**Comment by raveenb** [comment]
i am also facing the same problem, my sentry logs are filled with this error

**Comment by Actticus** [comment]
@raveenb I downgraded fastapi version to 0.68.2 and BrokenResourceError is "fixed"

**Comment by raveenb** [comment]
@Actticus thanks for the suggestion, let me give it a try

**Comment by nsoranzo** [comment]
> This is fixed in Starlette v0.17.0, hopefully FastAPI bumps starlette again on next release

I think this can be closed now that fastapi 0.71.0 bumped Starlette to 0.17.1 .

**Comment by havardthom** [comment]
I have tested FastAPI v0.71.0 in my project and the BrokenResourceError is fixed.

**Comment by alejosv** [comment]
> I have tested FastAPI v0.71.0 in my project and the BrokenResourceError is fixed.

@havardthom are you use a middleware?

**Comment by havardthom** [comment]
> 



> > I have tested FastAPI v0.71.0 in my project and the BrokenResourceError is fixed.
> 
> @havardthom are you use a middleware?

Yes

**Comment by henriklindgren** [comment]
> > This is fixed in Starlette v0.17.0, hopefully FastAPI bumps starlette again on next release
> 
> I think this can be closed now that fastapi 0.71.0 bumped Starlette to 0.17.1 .

> I have tested FastAPI v0.71.0 in my project and the BrokenResourceError is fixed.


Still seeing this with
```
starlette==0.17.1
fastapi==0.71.0
```
```
BrokenResourceError: null
  File "uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "starlette/middleware/base.py", line 57, in __call__
    task_group.cancel_scope.cancel()
  File "anyio/_backends/_asyncio.py", line 567, in __aexit__
    raise exceptions[0]
  File "starlette/middleware/base.py", line 30, in coro
    await self.app(scope, request.receive, send_stream.send)
  File "starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "starlette/exceptions.py", line 82, in __call__
    raise exc
  File "starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "starlette/responses.py", line 139, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "starlette/exceptions.py", line 68, in sender
    await send(message)
  File "anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
```

Using the middleware db session pattern, similar to
```
@app.middleware('http')
async def db_session_middleware(request, call_next):
    try:
        request.state.db = SessionLocal()
        response = await call_next(request)
        request.state.db.commit()
    except Exception:
        request.state.db.rollback()
        response = Response('Internal server error', status_code=500)
    finally:
        request.state.db.close()
    return response
```

**Comment by prsangappa** [comment]
Still seeing this issue

```
starlette==0.17.1
fastapi==0.72.0
```

```
WouldBlock: null
  File "anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "anyio/streams/memory.py", line 186, in send_nowait
    raise WouldBlock
BrokenResourceError: null
  File "ddtrace/contrib/asgi/middleware.py", line 178, in __call__
    reraise(exc_type, exc_val, exc_tb)
  File "six.py", line 719, in reraise
    raise value
  File "ddtrace/contrib/asgi/middleware.py", line 173, in __call__
    return await self.app(scope, receive, wrapped_send)
  File "starlette/exceptions.py", line 82, in __call__
    raise exc
  File "starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "starlette/responses.py", line 156, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "starlette/exceptions.py", line 68, in sender
    await send(message)
  File "ddtrace/contrib/asgi/middleware.py", line 170, in wrapped_send
    return await send(message)
  File "starlette_exporter/middleware.py", line 132, in wrapped_send
    await send(message)
  File "anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
```

**Comment by henriklindgren** [comment]
@prsangappa Could you check what version you have for anyio? I went to 3.5.0 now and so far so good (together with fastapi 0.72.0 and starlette 0.17.1). Asking because I saw the following change went into anyio 3.5.0, see https://github.com/agronholm/anyio/commit/3877a80776833245fd5c558646b6169058ec6ad7#diff-81debd08048a10458b2748d33fe4c0229c1697dc0faa027ccd6bc9d4262137ffR138

**Comment by prsangappa** [comment]
I have `anyio 3.5.0`.

**Comment by henriklindgren** [comment]
> so far so good

Nope, got another one

```
WouldBlock: null
  File "anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "anyio/streams/memory.py", line 186, in send_nowait
    raise WouldBlock

BrokenResourceError: null
  File "starlette/exceptions.py", line 82, in __call__
    raise exc
  File "starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "starlette/responses.py", line 156, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "starlette/exceptions.py", line 68, in sender
    await send(message)
  File "anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
```

**Comment by jangia** [comment]
Still experiencing this issue:
- fastapi == 0.72.0
- starlette == 0.17.1

**Comment by larsbijl** [comment]
In case it helps others, We ran into this issue when running in k8s with low memory/cpu limits.

**Comment by andgineer** [comment]
see this issue on AWS Fargate with 24G RAM and "4096" CPU - plenty of resources
fastapi == 0.70.0
starlette == 0.17.1

**Comment by pietdaniel** [comment]
Seeing this issue on EKS with plenty of resources. We are using [ddtrace](https://github.com/DataDog/dd-trace-py) though I doubt this is causing the issue. We are running using [uvicorn](https://www.uvicorn.org/) as our ASGI server.

deps

```python
ddtrace==0.57.3
fastapi==0.73.0
starlette==0.17.1
uvicorn==0.17.4
```

full stack trace

```python
anyio.BrokenResourceError

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/memory.py", line 186, in send_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/asgi/middleware.py", line 173, in __call__
    return await self.app(scope, receive, wrapped_send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 156, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/usr/local/lib/python3.9/site-packages/ddtrace/contrib/asgi/middleware.py", line 170, in wrapped_send
    return await send(message)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError

anyio.BrokenResourceError
```

App invocation

```Dockerfile
CMD ["ddtrace-run", "uvicorn", "app:app"]
```

**Comment by pfribourg-ias** [comment]
Add the issue with
```
fastapi==0.70.1
starlette==0.16.0
uvicorn[standard]==0.13.3
```

fixed by switching to 
```
fastapi==0.74.1
starlette==0.17.1
uvicorn[standard]==0.17.5
```

also as we are using Gino and gino-starlette require starlette v0.16.0 I add to import gino-starlette src into my project to allow switching to starlette v0.17.1

**Comment by tiangolo** [comment]
I have been debugging and trying to replicate this, I used the original example:

```Python
import time
from fastapi import FastAPI, Request


app = FastAPI()


@app.middleware("http")
async def middleware(request: Request, call_next):
    return await call_next(request)


@app.get("/")
def read_root():
    time.sleep(4)
    return {"Hello": "World"}
```

With the script:

```Python
import requests

r = requests.get(f"http://127.0.0.1:8000", timeout=2)
```

This means that the server starts handling the request, and before returning the response, the client disconnects. I was only able to replicate the error in an old environment with `starlette-0.15.0`, but the error disappeared after upgrading FastAPI to the latest (currently `0.75.0`) that includes Starlette version `0.17.1`.

---

I also tried making the server start the response in a streaming response, and making the client close the connection before the server ends sending the response, e.g.:

```Python
import time

from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse

app = FastAPI()


@app.middleware("http")
async def middleware(request: Request, call_next):
    return await call_next(request)


@app.get("/stream")
def main():
    def stream():
        for i in range(10000):
            yield str(i)
            time.sleep(1)
            if i == 10:
                break

    return StreamingResponse(stream(), media_type="mp4/video")
```

...but still, that didn't trigger the exception either.

---

If anyone is still experiencing this, please help me find a way to replicate your error. The versions of the packages alone don't seem to be enough to replicate it with the examples above. If you have some particular example that breaks with the current versions and that can be replicated, that would be the best way to figure out what's happening (if there's anything still happening) and then solve it, thanks! :bow:

**Comment by cbernet** [comment]
I just got this issue as well for the first time, with fastapi 0.75.0. 
I'm running on a kubernetes cluster from the most recent python 3.9 image.

Maybe it's related : this issue occured only a few days after I set up sentry, with its ASGI middleware : https://docs.sentry.io/platforms/python/guides/asgi/

Here is how I integrated it in FastAPI : 

```
from sentry_sdk.integrations.asgi import SentryAsgiMiddleware


alembic.check_revisions()
app = FastAPI(version="1.1.0")

sentry_url = os.environ.get("SENTRY_URL")
if sentry_url:

    def strip_paths(sampling_context):
        path = sampling_context["asgi_scope"]["path"]
        if path in ["/healthz"]:
            return 0.0
        else:
            return 1.0

    sentry_sdk.init(
        sentry_url,
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        # We recommend adjusting this value in production.
        # traces_sample_rate=0.,
        traces_sampler=strip_paths,
        # before_send=strip_paths,
    )
    app.add_middleware(SentryAsgiMiddleware)
```

By the way, the exception occured in the `/healthz` endpoint, that I'm filtering out of sentry. It's quite rare, as Kubernetes makes tens of thousands of calls to this endpoint per day. The exception occured only once so far.

**Comment by haf** [comment]
I'm also getting this, very often, when using the CPU and network on the machine.

```
ERROR:    event="" timestamp=2022-05-03T06:45:08+0000 name="serve_mmm" source="mid.py:25"
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 193, in send
    self.send_nowait(item)
  File "/venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 186, in send_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/svc/serve-mmm/serve_mmm/mid.py", line 23, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/venv/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/venv/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/venv/lib/python3.9/site-packages/starlette/routing.py", line 64, in app
    await response(scope, receive, send)
  File "/venv/lib/python3.9/site-packages/starlette/responses.py", line 156, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 68, in sender
    await send(message)
  File "/app/svc/serve-mmm/serve_mmm/mid.py", line 20, in send_wrapper
    await send(message)
  File "/venv/lib/python3.9/site-packages/opentelemetry/instrumentation/asgi/__init__.py", line 409, in otel_send
    await send(message)
  File "/venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 205, in send
    raise BrokenResourceError
```

All the middleware you see (like mid.py) just calls the next handler in the middlware chain.

**Comment by liavkoren** [comment]
@tiangolo [I have a set of files that will reliably, and quickly reproduce an AnyIO stream error when using ContextMiddleware, but don't when ContextMiddleware is removed.](https://gist.github.com/liavkoren/3a7b2773e3ede681d2786bfd83bc14a7) 

The stack trace is not the same as the ones above, but it looks like it's touching  a lot of the same modules. I put this together because we've been having the same `
anyio.BrokenResourceError` errors in production, using fastapi 0.75.2.

**Comment by haf** [comment]
@liavkoren The problem being most of these inheritance:s are deep inside libraries, right?

**Comment by liavkoren** [comment]
We switched our the CorrelationIdPlugin to use RawContextMiddleware (which doesn't inherit from the starlette baseMiddleware) and deployed that to prod yesterday at 4pm. We haven't had any BrokenResourceErrors since:

```
app.add_middleware(RawContextMiddleware, plugins=[plugins.CorrelationIdPlugin()])
```

We have a different service which has never run into this issue, and it sets up middleware like so:

```

middleware = [
    Middleware(RawContextMiddleware),
    Middleware(ContextMiddleware, plugins=(plugins.CorrelationIdPlugin(),)),
    Middleware(CORSMiddleware...)
]
```

More of a workaround than a fix (what the heck is RawContextMiddleware doing? How is it different from starlette baseMiddleware? Is this bad? Who knows! I looked at the source for both very briefly and decided that things were not dire enough that I needed to go down those rabbit holes right now.] However, it *has* silenced the BrokenResourceErrors coming out of our /health endpoint since 4pm yesterday, and all our tests still pass and no one has yelled at us yet so.. cool?

**Comment by MrSalman333** [comment]
> 

same

**Comment by MrSalman333** [comment]
> I just got this issue as well for the first time, with fastapi 0.75.0. I'm running on a kubernetes cluster from the most recent python 3.9 image.
> 
> Maybe it's related : this issue occured only a few days after I set up sentry, with its ASGI middleware : https://docs.sentry.io/platforms/python/guides/asgi/
> 
> Here is how I integrated it in FastAPI :
> 
> ```
> from sentry_sdk.integrations.asgi import SentryAsgiMiddleware
> 
> 
> alembic.check_revisions()
> app = FastAPI(version="1.1.0")
> 
> sentry_url = os.environ.get("SENTRY_URL")
> if sentry_url:
> 
>     def strip_paths(sampling_context):
>         path = sampling_context["asgi_scope"]["path"]
>         if path in ["/healthz"]:
>             return 0.0
>         else:
>             return 1.0
> 
>     sentry_sdk.init(
>         sentry_url,
>         # Set traces_sample_rate to 1.0 to capture 100%
>         # of transactions for performance monitoring.
>         # We recommend adjusting this value in production.
>         # traces_sample_rate=0.,
>         traces_sampler=strip_paths,
>         # before_send=strip_paths,
>     )
>     app.add_middleware(SentryAsgiMiddleware)
> ```
> 
> By the way, the exception occured in the `/healthz` endpoint, that I'm filtering out of sentry. It's quite rare, as Kubernetes makes tens of thousands of calls to this endpoint per day. The exception occured only once so far.

same

**Comment by stregouet** [comment]
First thanks tiangolo and all others fastapi contributors for providing such a cool and valuable tool!

I'm currently migrating a wsgi app to a full fastapi app and I'm also facing this BrokenResourceError.

Here is a minimal repro:

app.py
```python
import time
from fastapi import FastAPI, Request
from fastapi.middleware.wsgi import WSGIMiddleware

import fla

app = FastAPI()


@app.middleware("http")
async def middleware(request: Request, call_next):
    return await call_next(request)


@app.get("/")
def read_root():
    time.sleep(4)
    return {"Hello": "World from fastpi route"}

app.mount("/wsgi", WSGIMiddleware(fla.app), name="flask")
```

fla.py
```python
import time
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello_world():
    time.sleep(4)
    return "<p>Hello, World! from flask route</p>"
```

client.py
```python
import requests

r = requests.get(f"http://127.0.0.1:8000/wsgi/", timeout=2)
```

I run `uvicorn app:app` and then `python client.py` and I get `BrokenResourceError`. 

Finally here is libraries versions:

```
fastapi           0.77.1
starlette         0.19.1
uvicorn           0.17.6
```

The relevant part is combination of `app.middleware("http")` and `WSGIMiddleware` removing one or the other and then `BrokenResourceError` disappears. Also note that requesting fastapi route is fine, only wsgi route generates the error.

**Comment by don4of4** [comment]
@cbernet We are also seeing this issue when using Sentry.io.  Did you end up coming up with a solution?

**Comment by cbernet** [comment]
@don4of4 we didn't try and find a solution as the problem is very rare. It only happened once since my first report. I can't really conclude about sentry. In fact, without sentry, it could be that we would still be unaware of this issue. So maybe sentry simply revealed this issue, and it's unrelated.

**Comment by panla** [comment]
### env

- fastapi==0.78.0
- starlette==0.19.1
- loguru==0.6.0
- httptools==0.4.0
- anyio==3.6.1
- uvicorn==0.17.6
- uvloop==0.16.0

### code

```python
from loguru import logger

logger.remove()

PATH = './x.log'
LEVEL = 'INFO'

logger.add(
    PATH, level=LEVEL, rotation="00:00", backtrace=True, diagnose=True, enqueue=True, compression='tar.gz'
)
```

### error

```text
00:00:08.886 | ERROR    | apps.libs.exception:log_message:20 - Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/memory.py", line 209, in send
    self.send_nowait(item)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/memory.py", line 202, in send_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 68, in app
    await response(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 162, in __call__
    await send({"type": "http.response.body", "body": self.body})
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in _send
    await send(message)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 79, in sender
    await send(message)
  File "/usr/local/lib/python3.9/site-packages/anyio/streams/memory.py", line 221, in send
    raise BrokenResourceError
anyio.BrokenResourceError
```

### desc

```text
had appeared once,
at 00:00 a big log file ---> x.log.tar.gz 
and get error.

don't know whose fault it is, loguru?, fastapi? starlette? anyio?
```

**Comment by JarroVGIT** [comment]
Do you use `BaseHTTPMiddleware` somewhere in your code? Either directly like:
```python
class CustomMiddleware(BaseHTTPMiddleware:
    pass
```
 or indirectly like:
```python
@app.middleware('http')
def middlewarefunc():
    pass
```

I found that most people above are experiencing this with that particular middleware, which actually uses MemoryStream of anyio.
