### ISSUE TITLE
[BUG] Router level Security dependency blocks route level dependency

### ISSUE THREAD

**Issue by elyobo** [tiangolo/fastapi#469]
**Describe the bug**
If I define a route level `Security` dependency in a router, then define a `Security` dependency in the dependencies when adding the router to an app, then the route level dependency is ignored.

**To Reproduce**

Excerpted example.

A router defines a dependency with a scope.

```
data_router = APIRouter()                                                           
@router.get(                                                                   
    '/sales',                                                                  
    dependencies=[Security(get_current_user, scopes=['sales'])],               
    )                                                                          
def get_sales():
  pass
```

Another router includes that router, defining another dependency

```
from .data import data_router
api_router = APIRouter()                                                           
api_router.include_router(                                                      
    data_router,                                                                
    prefix='/data',                                                             
    dependencies=[Security(get_current_user, scopes=[])],                       
    )                                                                           
```

The `sales` scope does not appear in the `SecurityScopes` scopes when validating the scopes.  Defining `Depends(get_current_user)` instead has the same problem (my original version; not all routes require the same scope, but I have a fallback requirement for a signed in user at least).  Removing the dependency _entirely_, e.g. below, does get the correct scope in `SecurityScopes`.

```
from .data import data_router
api_router = APIRouter()                                                           
api_router.include_router(                                                      
    data_router,                                                                
    prefix='/data',                                                             
    )                                                                           
```

**Expected behavior**

The scopes from all `Security` definitions in the dependency tree should be required (e.g. any defined when including the router, and any on the routes that the router provides).

**Screenshots**
N/A

**Environment:**
 - OS: Ubuntu 19.04
 - FastAPI Version: 0.35.0
- Python version: 3.7.3

**Comment by tiangolo** [comment]
Thanks for the report @elyobo ! I'll check it.

**Comment by vladz** [comment]
Old question but actual to me. I faced the same problem. `use_cache=False` param helped.
```
data_router = APIRouter()                                                           
@router.get(                                                                   
    '/sales',                                                                  
    dependencies=[Security(get_current_user, scopes=['sales'], use_cache=False)],               
    )                                                                          
def get_sales():
  pass
```

**Comment by tiangolo** [comment]
I think this was solved in https://github.com/tiangolo/fastapi/pull/2945

That fix is available in FastAPI `0.80.0`, could you check if everything is working as you expect?

Otherwise, could you create a minimal self-contained example that reproduced the issue in code? Something that I can run here and see how it breaks to be able to understand the problem and handle it.

**Comment by elyobo** [comment]
Sorry, I'm no longer using FastAPI (it's awesome, just mainly doing javascript dev these days - nothing of the same standard over there :cry:) so am unable to test the original issue. Hopefully @vladz can confirm, otherwise feel free to close.

**Comment by tiangolo** [comment]
Thanks for the reply @elyobo! :coffee:

**Comment by kfdl** [comment]
Hello @tiangolo, 
Thank you for this amazing product I use it for every api project in python.
Currently I'm using the 0.85.0 version of fastapi but I still have the issue what do you recommend to do in this type of issue? 

Thank you for your work :)

Best regards,

**Comment by tiangolo** [comment]
@kfdl could you please create a new issue with a minimal, self-contained example that I can copy paste and run here to replicate your problem, please?
